name: reviewdog
on: push

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./ # Uses an action in the root directory
        with:
          reporter: github-check
          fail_on_error: true
          level: warning
          debug: true
